- name: Backup `VirtualBox VMs` folder on each host
  hosts: all
  gather_facts: true

  tasks:
    - name: Set backup directory name
      set_fact: 
        backupDir: "~/VirtualBox VMs Backup/{{ ansible_date_time.iso8601_basic }}"
    - name: Create backup directory
      file:
        path: "{{ backupDir }}"
        state: directory
    - name: Copy the folder to the backup
      copy:
        remote_src: true
        src: ~/VirtualBox VMs/
        dest: "{{ backupDir }}"

