- name: Suspend operation of target VMs
  hosts: "{{ vars.hosts }}"
  become: false

  tasks:
    # Check if vagrant dir exists
    - include_tasks: ../common/check-vagrant-dir.yaml
    - name: Set vm_hostnames var for checking
      set_fact:
        vm_hostnames: "{{ vars.hostToVms[inventory_hostname] }}"
    - include_tasks: ../common/check-vm-hostnames.yaml
    - name: Vagrant suspend
      delegate_to: localhost
      args:
        executable: /bin/bash
      ansible.builtin.shell: "ssh {{ ansible_user }}@{{ inventory_hostname }} 'cd {{ vars[inventory_hostname].vagrantDir }}; vagrant suspend {{ vars.hostToVms[inventory_hostname] | join(\" \") }}' >> /api/logs/{{ inventory_hostname }}-vagrant-suspend-stdout"
      register: out
      changed_when: out.rc == 0
