    - name: Check that VM hostnames are valid
      assert:
        that: 
        - "'{{ item }}' is regex('^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$')"
      loop: "{{ vm_hostnames }}"